# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stack.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(894, 726)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.show_stack = QtWidgets.QTableWidget(self.centralwidget)
        self.show_stack.setGeometry(QtCore.QRect(40, 30, 401, 551))
        self.show_stack.setObjectName("show_stack")
        self.show_stack.setColumnCount(0)
        self.show_stack.setRowCount(0)
        self.task_info = QtWidgets.QLabel(self.centralwidget)
        self.task_info.setGeometry(QtCore.QRect(690, 10, 161, 131))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.task_info.setFont(font)
        self.task_info.setFrameShape(QtWidgets.QFrame.Box)
        self.task_info.setText("")
        self.task_info.setObjectName("task_info")
        self.stack_info = QtWidgets.QLabel(self.centralwidget)
        self.stack_info.setGeometry(QtCore.QRect(510, 180, 341, 401))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.stack_info.setFont(font)
        self.stack_info.setFrameShape(QtWidgets.QFrame.Box)
        self.stack_info.setText("")
        self.stack_info.setObjectName("stack_info")
        self.forward_button = QtWidgets.QPushButton(self.centralwidget)
        self.forward_button.setGeometry(QtCore.QRect(740, 640, 101, 31))
        self.forward_button.setObjectName("forward_button")
        self.method_info = QtWidgets.QLabel(self.centralwidget)
        self.method_info.setGeometry(QtCore.QRect(510, 10, 161, 131))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        self.method_info.setFont(font)
        self.method_info.setFrameShape(QtWidgets.QFrame.Box)
        self.method_info.setText("")
        self.method_info.setObjectName("method_info")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(520, 640, 101, 31))
        self.back_button.setObjectName("back_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 600, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(740, 150, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(650, 590, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(560, 140, 71, 20))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 894, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.forward_button.setText(_translate("MainWindow", "前进"))
        self.back_button.setText(_translate("MainWindow", "后退"))
        self.label.setText(_translate("MainWindow", "display_stack"))
        self.label_2.setText(_translate("MainWindow", "task_info"))
        self.label_3.setText(_translate("MainWindow", "stack_info"))
        self.label_4.setText(_translate("MainWindow", "now_method"))
